name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Update Snake Game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4  # Versão mais recente

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: bb9leko
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            
      - name: Commit e push da animação gerada
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/
          
          # Verificar se há mudanças
          if git diff --cached --quiet; then
            echo "✅ Nenhuma mudança para commitar"
          else
            echo "📝 Commitando mudanças..."
            git commit -m "🐍 Atualização da animação da cobra"
            git push
            echo "✅ Push realizado com sucesso"
          fi
